// Login
export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const REGISTER_USER = 'REGISTER_USER'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILED = 'REGISTER_FAILED'

export const REQUEST_BCCS = 'REQUEST_BCCS'
export const REQUEST_BCCS_SUCCESS = 'REQUEST_BCCS_SUCCESS'
export const REQUEST_BCCS_FAILED = 'REQUEST_BCCS_FAILED'

export const ACTIVE_PIN = 'ACTIVE_PIN'
export const ACTIVE_PIN_SUCCESS = 'ACTIVE_PIN_SUCCESS'
export const ACTIVE_PIN_FAILED = 'ACTIVE_PIN_FAILED'

export const SET_LOGGED_IN = 'SET_LOGGED_IN'

export const SET_INFO_ACCOUNT = 'SET_INFO_ACCOUNT'

export const VALIDATE_PIN = 'VALIDATE_PIN'
export const VALIDATE_PIN_SUCCESS = 'VALIDATE_PIN_SUCCESS'
export const VALIDATE_PIN_FAILED = 'VALIDATE_PIN_FAILED'

export const LOGOUT_USER = 'logout_user'

// Set tabs for View Pager
export const SET_TAB = 'set_tab'

// Navigate between several scene
export const NAVIGATE_FORWARD = 'navigate_forward'
export const NAVIGATE_BACK = 'navigate_back'

// Transfer
export const GET_ACCOUNT_INFO = 'GET_ACCOUNT_INFO'
export const GET_ACCOUNT_INFO_SUCCESS = 'GET_ACCOUNT_INFO_SUCCESS'
export const GET_ACCOUNT_INFO_FAILED = 'GET_ACCOUNT_INFO_FAILED'

export const ACCESS_INFO_WALLET_NON_WALLET = 'ACCESS_INFO_WALLET_NON_WALLET'
export const ACCESS_INFO_WALLET_NON_WALLET_SUCCESS = 'ACCESS_INFO_WALLET_NON_WALLET_SUCCESS'
export const ACCESS_INFO_WALLET_NON_WALLET_FAILED = 'ACCESS_INFO_WALLET_NON_WALLET_FAILED'

export const ACCESS_INFO_WALLET_WALLET = 'ACCESS_INFO_WALLET_WALLET'
export const ACCESS_INFO_WALLET_WALLET_SUCCESS = 'ACCESS_INFO_WALLET_WALLET_SUCCESS'
export const ACCESS_INFO_WALLET_WALLET_FAILED = 'ACCESS_INFO_WALLET_WALLET_FAILED'

export const CONFIRM_PIN = 'CONFIRM_PIN'
export const CONFIRM_PIN_SUCCESS = 'CONFIRM_PIN_SUCCESS'
export const CONFIRM_PIN_FAILED = 'CONFIRM_PIN_FAILED'

export const GET_OTP = 'GET_OTP'
export const GET_OTP_SUCCESS = 'GET_OTP_SUCCESS'
export const GET_OTP_FAILED = 'GET_OTP_FAILED'

export const REQUEST_PAYMENT_ELECTRIC = 'REQUEST_PAYMENT_ELECTRIC'
export const REQUEST_PAYMENT_ELECTRIC_SUCCESS = 'REQUEST_PAYMENT_ELECTRIC_SUCCESS'
export const REQUEST_PAYMENT_ELECTRIC_FAILED = 'REQUEST_PAYMENT_ELECTRIC_FAILED'

export const REQUEST_BALANCE = 'REQUEST_BALANCE'
export const REQUEST_BALANCE_SUCCESS = 'REQUEST_BALANCE_SUCCESS'
export const REQUEST_BALANCE_FAILED = 'REQUEST_BALANCE_FAILED'

export const GET_TRANSACTION_HISTORY = 'GET_TRANSACTION_HISTORY'
export const GET_TRANSACTION_HISTORY_SUCCESS = 'GET_TRANSACTION_HISTORY_SUCCESS'
export const GET_TRANSACTION_HISTORY_FAILED = 'GET_TRANSACTION_HISTORY_FAILED'

export const GET_PAYMENT_INFO = 'GET_PAYMENT_INFO'
export const GET_PAYMENT_INFO_SUCCESS = 'GET_PAYMENT_INFO_SUCCESS'
export const GET_PAYMENT_INFO_FAILED = 'GET_PAYMENT_INFO_FAILED'

export const REQUEST_TOP_UP = 'REQUEST_TOP_UP'
export const REQUEST_TOP_UP_SUCCESS = 'REQUEST_TOP_UP_SUCCESS'
export const REQUEST_TOP_UP_FAILED = 'REQUEST_TOP_UP_FAILED'

export const REQUEST_CASH_OUT = 'REQUEST_CASH_OUT'
export const REQUEST_CASH_OUT_SUCCESS = 'REQUEST_CASH_OUT_SUCCESS'
export const REQUEST_CASH_OUT_FAILED = 'REQUEST_CASH_OUT_FAILED'

export const REQUEST_CASH_IN = 'REQUEST_CASH_IN'
export const REQUEST_CASH_IN_SUCCESS = 'REQUEST_CASH_IN_SUCCESS'
export const REQUEST_CASH_IN_FAILED = 'REQUEST_CASH_IN_FAILED'

export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'
export const CHANGE_LOCAL_LANGUAGE = 'CHANGE_LOCAL_LANGUAGE'
export const CHANGE_LANGUAGE_SUCCESS = 'CHANGE_LANGUAGE_SUCCESS'
export const CHANGE_LANGUAGE_LOCAL_SUCCESS = 'CHANGE_LANGUAGE_LOCAL_SUCCESS'
export const CHANGE_LANGUAGE_FAILED = 'CHANGE_LANGUAGE_FAILED'

export const CHANGE_PIN = 'CHANGE_PIN'
export const CHANGE_PIN_SUCCESS = 'CHANGE_PIN_SUCCESS'
export const CHANGE_PIN_FAILED = 'CHANGE_PIN_FAILED'

//
export const TRANSFER_OTHER_TO_OTHER = 'TRANSFER_OTHER_TO_OTHER'
export const TRANSFER_OTHER_TO_OTHER_SUCCESS = 'TRANSFER_OTHER_TO_OTHER_SUCCESS'
export const TRANSFER_OTHER_TO_OTHER_FAILED = 'TRANSFER_OTHER_TO_OTHER_FAILED'

export const SEARCH_DIR_TRANS_HIS = 'SEARCH_DIR_TRANS_HIS'
export const SEARCH_DIR_TRANS_HIS_SUCCESS = 'SEARCH_DIR_TRANS_HIS_SUCCESS'
export const SEARCH_DIR_TRANS_HIS_FAILED = 'SEARCH_DIR_TRANS_HIS_FAILED'

export const AGENT_REQUEST_EMONEY = 'AGENT_REQUEST_EMONEY'
export const AGENT_REQUEST_EMONEY_SUCCESS = 'AGENT_REQUEST_EMONEY_SUCCESS'
export const AGENT_REQUEST_EMONEY_FAILED = 'AGENT_REQUEST_EMONEY_FAILED'

export const AGENT_REQ_BANK_MONEY = 'AGENT_REQ_BANK_MONEY'
export const AGENT_REQ_BANK_MONEY_SUCCESS = 'AGENT_REQ_BANK_MONEY_SUCCESS'
export const AGENT_REQ_BANK_MONEY_FAILED = 'AGENT_REQ_BANK_MONEY_FAILED'

export const AGENT_CASH_OUT = 'AGENT_CASH_OUT'
export const AGENT_CASH_OUT_SUCCESS = 'AGENT_CASH_OUT_SUCCESS'
export const AGENT_CASH_OUT_FAILED = 'AGENT_CASH_OUT_FAILED'

export const AGENT_REG_FOR_USER = 'AGENT_REG_FOR_USER'
export const AGENT_REG_FOR_USER_SUCCESS = 'AGENT_REG_FOR_USER_SUCCESS'
export const AGENT_REG_FOR_USER_FAILED = 'AGENT_REG_FOR_USER_FAILED'

export const GET_COMMISSION_THIS_MONTH = 'GET_COMMISSION_THIS_MONTH'
export const GET_COMMISSION_THIS_MONTH_SUCCESS = 'GET_COMMISSION_THIS_MONTH_SUCCESS'
export const GET_COMMISSION_THIS_MONTH_FAILED = 'GET_COMMISSION_THIS_MONTH_FAILED'

export const GET_COMMISSION_LAST_MONTH = 'GET_COMMISSION_LAST_MONTH'
export const GET_COMMISSION_LAST_MONTH_SUCCESS = 'GET_COMMISSION_LAST_MONTH_SUCCESS'
export const GET_COMMISSION_LAST_MONTH_FAILED = 'GET_COMMISSION_LAST_MONTH_FAILED'

export const GET_AGENT_LOCATION = 'GET_AGENT_LOCATION'
export const GET_AGENT_LOCATION_SUCCESS = 'GET_AGENT_LOCATION_SUCCESS'
export const GET_AGENT_LOCATION_FAILED = 'GET_AGENT_LOCATION_FAILED'

export const PING = "PING"
export const PING_SUCCESS = "PING_SUCCESS"
export const PING_FALSE = "PING_FALSE"

export const CHECK_FUNDER = 'CHECK_FUNDER'
export const CHECK_FUNDER_SUCCESS = 'CHECK_FUNDER_SUCCESS'
export const CHECK_FUNDER_FALSE = 'CHECK_FUNDER_FALSE'

// By thavithong
export const UPLOAD_IMAGE_REQUEST = 'UPLOAD_IMAGE_REQUEST'
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE'
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS'
export const UPLOAD_IMAGE_FALSE = 'UPLOAD_IMAGE_FALSE'
export const SEARCH_UPLOAD_IMAGE = 'SEARCH_UPLOAD_IMAGE'
export const SEARCH_UPLOAD_IMAGE_SUCCESS = 'SEARCH_UPLOAD_IMAGE_SUCCESS'
export const SEARCH_UPLOAD_IMAGE_FALSE = 'SEARCH_UPLOAD_IMAGE_FALSE'
export const STORE_IMAGE = 'STORE_IMAGE'
export const STORE_IMAGE_SUCCESS = 'STORE_IMAGE_SUCCESS'
export const STORE_IMAGE_FALSE = 'STORE_IMAGE_FALSE'

//By bopby
export const BUY_LOTTERY = 'BUY_LOTTERY'
export const BUY_LOTTERY_SUCCESS = 'BUY_LOTTERY_SUCCESS'
export const BUY_LOTTERY_FALSE = 'BUY_LOTTERY_FALSE'

export const SALE_LOTTERY = 'SALE_LOTTERY'
export const SALE_LOTTERY_SUCCESS = 'SALE_LOTTERY_SUCCESS'
export const SALE_LOTTERY_FALSE = 'SALE_LOTTERY_FALSE'

export const HISTORY_LOTTERY = 'HISTORY_LOTTERY'
export const HISTORY_LOTTERY_SUCCESS = 'HISTORY_LOTTERY_SUCCESS'
export const HISTORY_LOTTERY_FALSE = 'HISTORY_LOTTERY_FALSE'

export const LUCKY_LOTTERY = 'LUCKY_LOTTERY'
export const LUCKY_LOTTERY_SUCCESS = 'LUCKY_LOTTERY_SUCCESS'
export const LUCKY_LOTTERY_FALSE = 'LUCKY_LOTTERY_FALSE'

export const CHECK_BARCODE = 'CHECK_BARCODE'
export const CHECK_BARCODE_SUCCESS = 'CHECK_BARCODE_SUCCESS'
export const CHECK_BARCODE_FALSE = 'CHECK_BARCODE_FALSE'

export const REQUEST_SETUP_PIN = 'REQUEST_SETUP_PIN'
export const REQUEST_SETUP_PIN_SUCCESS = 'REQUEST_SETUP_PIN_SUCCESS'
export const REQUEST_SETUP_PIN_FALSE = 'REQUEST_SETUP_PIN_FALSE'

//TOP UP ETL CHECK_ACCOUNT_ETL
export const CHECK_ACCOUNT_ETL = 'CHECK_ACCOUNT_ETL'
export const CHECK_ACCOUNT_ETL_SUCCESS = 'CHECK_ACCOUNT_ETL_SUCCESS'
export const CHECK_ACCOUNT_ETL_FALSE = 'CHECK_ACCOUNT_ETL_FALSE'

// CHECK FEE TOP UP ETL
export const CHECK_FEE_TOPUP_ETL = 'CHECK_FEE_TOPUP_ETL'
export const CHECK_FEE_TOPUP_ETL_SUCCESS = 'CHECK_FEE_TOPUP_ETL_SUCCESS'
export const CHECK_FEE_TOPUP_ETL_FALSE = 'CHECK_FEE_TOPUP_ETL_FALSE'


// GET OTP TOPUP
export const GET_OTP_ETL = 'GET_OTP_ETL'
export const GET_OTP_ETL_SUCCESS = 'GET_OTP_ETL_SUCCESS'
export const GET_OTP_ETL_FAILED = 'GET_OTP_ETL_FAILED'


//REQUEST_TOP_UP_ETL
export const REQUEST_TOP_UP_ETL = 'REQUEST_TOP_UP_ETL'
export const REQUEST_TOP_UP_ETL_SUCCESS = 'REQUEST_TOP_UP_ETL_SUCCESS'
export const REQUEST_TOP_UP_ETL_FAILED = 'REQUEST_TOP_UP_ETL_FAILED'



//ACCUONT BANK
export const CHECK_ACCUONT_BANK = 'CHECK_ACCUONT_BANK'
export const CHECK_ACCUONT_BANK_SUCCESS = 'CHECK_ACCUONT_BANK_SUCCESS'
export const CHECK_ACCUONT_BANK_FALSE = 'CHECK_ACCUONT_BANK_FALSE'

//CHECK FEE BANK
export const CHECK_FEE_BANK = 'CHECK_FEE_BANK'
export const CHECK_FEE_BANK_SUCCESS = 'CHECK_FEE_BANK_SUCCESS'
export const CHECK_FEE_BANK_FALSE = 'CHECK_FEE_BANK_FALSE'

//GET OTP LVB
export const GET_OTP_BANK = 'GET_OTP_BANK'
export const GET_OTP_BANK_SUCCESS = 'GET_OTP_BANK_SUCCESS'
export const GET_OTP_BANK_FAILED = 'GET_OTP_BANK_FAILED'

//TRANSFER_EWALLET_TO_BANK
export const TRANSFER_EWALLET_TO_BANK = 'TRANSFER_EWALLET_TO_BANK'
export const TRANSFER_EWALLET_TO_BANK_SUCCESS = 'TRANSFER_EWALLET_TO_BANK_SUCCESS'
export const TRANSFER_EWALLET_TO_BANK_FAILED = 'TRANSFER_EWALLET_TO_BANK_FAILED'


export const CHECK_NEW_USER = 'CHECK_NEW_USER'
export const CHECK_NEW_USER_SUCCESS = 'CHECK_NEW_USER_SUCCESS'
export const CHECK_NEW_USER_FAILED = 'CHECK_NEW_USER_FAILED'


export const CHECK_ADD_USER = 'CHECK_ADD_USER'
export const CHECK_ADD_USER_SUCCESS = 'CHECK_ADD_USER_SUCCESS'
export const CHECK_ADD_USER_FAILED = 'CHECK_ADD_USER_FAILED'

// checkPresentee
export const CHECK_PRESENTEE = 'CHECK_PRESENTEE'
export const CHECK_PRESENTEE_SUCCESS = 'CHECK_PRESENTEE_SUCCESS'
export const CHECK_PRESENTEE_FAILED = 'CHECK_PRESENTEE_FAILED'

export const CHECK_HISTORY_TRANFER = 'CHECK_HISTORY_TRANFER'
export const CHECK_HISTORY_TRANFER_SUCCESS = 'CHECK_HISTORY_TRANFER_SUCCESS'
export const CHECK_HISTORY_TRANFER_FAILED = 'CHECK_HISTORY_TRANFER_FAILED'


//ACCUONT BCCS
export const CHECK_ACCUONT_BCCS = 'CHECK_ACCUONT_BCCS'
export const CHECK_ACCUONT_BCCS_SUCCESS = 'CHECK_ACCUONT_BCCS_SUCCESS'
export const CHECK_ACCUONT_BCCS_FALSE = 'CHECK_ACCUONT_BCCS_FALSE'

//PAY_STAFF_DEBT
export const PAY_STAFF_DEBT = 'PAY_STAFF_DEBT'
export const PAY_STAFF_DEBT_SUCCESS = 'PAY_STAFF_DEBT_SUCCESS'
export const PAY_STAFF_DEBT_FALSE = 'PAY_STAFF_DEBT_FALSE'



export const GET_PAYMENT_INFO_SOKXAY = 'GET_PAYMENT_INFO_SOKXAY'
export const GET_PAYMENT_INFO_SUCCESS_SOKXAY = 'GET_PAYMENT_INFO_SUCCESS_SOKXAY'
export const GET_PAYMENT_INFO_FAILED_SOKXAY = 'GET_PAYMENT_INFO_FAILED_SOKXAY'


export const HISTORY_TRANFER = 'HISTORY_TRANFER'
export const HISTORY_TRANFER_SUCCESS = 'HISTORY_TRANFER_SUCCESS'
export const HISTORY_TRANFER_FAILED = 'HISTORY_TRANFER_FAILED'

// search
export const SEARCH_HISTORY_TRANFER = 'SEARCH_HISTORY_TRANFER'
export const SEARCH_HISTORY_TRANFER_SUCCESS = 'SEARCH_HISTORY_TRANFER_SUCCESS'
export const SEARCH_HISTORY_TRANFER_FAILED = 'SEARCH_HISTORY_TRANFER_FAILED'

export const CHECK_HISTORY_LOTTERY = 'CHECK_HISTORY_LOTTERY'
export const CHECK_HISTORY_LOTTERY_SUCCESS = 'CHECK_HISTORY_LOTTERY_SUCCESS'
export const CHECK_HISTORY_LOTTERY_FAILED = 'CHECK_HISTORY_LOTTERY_FAILED'

export const SEACRC_HISTORY_LOTTERY_TRANFER = 'SEACRC_HISTORY_LOTTERY_TRANFER'
export const SEACRC_HISTORY_LOTTERY_TRANFER_SUCCESS = 'SEACRC_HISTORY_LOTTERY_TRANFER_SUCCESS'
export const SEACRC_HISTORY_LOTTERY_TRANFER_FAILED = 'SEACRC_HISTORY_LOTTERY_TRANFER_FAILED'


export const GET_NUMBER_WIN = 'GET_NUMBER_WIN'
export const GET_NUMBER_WIN_SUCCESS = 'GET_NUMBER_WIN_SUCCESS'
export const GET_NUMBER_WIN_FAILED = 'GET_NUMBER_WIN_FAILED'


export const CHECK_VERSION = 'CHECK_VERSION'
export const CHECK_VERSION_SUCCESS = 'CHECK_VERSION_SUCCESS'
export const CHECK_VERSION_FAILED = 'CHECK_VERSION_FAILED'

export const CHECK_CONTRACT_NUMBER = 'CHECK_CONTRACT_NUMBER'
export const CHECK_CONTRACT_NUMBER_SUCCESS = 'CHECK_CONTRACT_NUMBER_SUCCESS'
export const CHECK_CONTRACT_NUMBER_FAILED = 'CHECK_CONTRACT_NUMBER_FAILED'


//PAY_LEASING_AEON_FAILED
export const PAY_LEASING_AEON = 'PAY_LEASING_AEON'
export const PAY_LEASING_AEON_SUCCESS = 'PAY_LEASING_AEON_SUCCESS'
export const PAY_LEASING_AEON_FAILED = 'PAY_LEASING_AEON_FAILED'


export const REQUES_CHECK_AGENT_ID = 'REQUES_CHECK_AGENT_ID'
export const REQUES_CHECK_AGENT_ID_SUCCESS = 'REQUES_CHECK_AGENT_ID_SUCCESS'
export const REQUES_CHECK_AGENT_ID_FAILED = 'REQUES_CHECK_AGENT_ID_FAILED'

export const REQUES_HISTORY_TRANFER = 'REQUES_HISTORY_TRANFER'
export const REQUES_HISTORY_TRANFER_SUCCESS = 'REQUES_HISTORY_TRANFER_SUCCESS'
export const REQUES_HISTORY_TRANFER_FAILED = 'REQUES_HISTORY_TRANFER_FAILED'

export const LOAD_MENU_BANK = 'LOAD_MENU_BANK'
export const LOAD_MENU_BANK_SUCCESS = 'LOAD_MENU_BANK_SUCCESS'
export const LOAD_MENU_BANK_FAILED = 'LOAD_MENU_BANK_FAILED'



export const GET_INFO_NCC_LOTTERY = 'GET_INFO_NCC_LOTTERY'
export const GET_INFO_NCC_LOTTERY_SUCCESS = 'GET_INFO_NCC_LOTTERY_SUCCESS'
export const GET_INFO_NCC_LOTTERY_FAILED = 'GET_INFO_NCC_LOTTERY_FAILED'

export const GET_SEARCH_TRANSACTION = 'GET_SEARCH_TRANSACTION'
export const GET_SEARCH_TRANSACTION_SUCCESS = 'GET_SEARCH_TRANSACTION_SUCCESS'
export const GET_SEARCH_TRANSACTION_FAILED = 'GET_SEARCH_TRANSACTION_FAILED'


export const APPROVAL_TRANSACTION = 'APPROVAL_TRANSACTION'
export const APPROVAL_TRANSACTION_SUCCESS = 'APPROVAL_TRANSACTION_SUCCESS'
export const APPROVAL_TRANSACTION_FAILED = 'APPROVAL_TRANSACTION_FAILED'

export const CHECK_NUMBER_CTTID = 'CHECK_NUMBER_CTTID'
export const CHECK_NUMBER_CTTID_SUCCESS = 'CHECK_NUMBER_CTTID_SUCCESS'
export const CHECK_NUMBER_CTTID_FAILED = 'CHECK_NUMBER_CTTID_FAILED'


export const GET_PROMOTION = 'GET_PROMOTION'
export const GET_PROMOTION_SUCCESS = 'GET_PROMOTION_SUCCESS'
export const GET_PROMOTION_FAILED = 'GET_PROMOTION_FAILED'

export const GET_PROMOTION_DETAIL = 'GET_PROMOTION_DETAIL'
export const GET_PROMOTION_DETAIL_SUCCESS = 'GET_PROMOTION_DETAIL_SUCCESS'
export const GET_PROMOTION_DETAIL_FAILED = 'GET_PROMOTION_DETAIL_FAILED'


export const CASH_OUT_WORD_BANK = 'CASH_OUT_WORD_BANK'
export const CASH_OUT_WORD_BANK_SUCCESS = 'CASH_OUT_WORD_BANK_SUCCESS'
export const CASH_OUT_WORD_BANK_FAILED = 'CASH_OUT_WORD_BANK_FAILED'


export const BUY_LOTTERY_NCC = 'BUY_LOTTERY_NCC'
export const BUY_LOTTERY_NCC_SUCCESS = 'BUY_LOTTERY_NCC_SUCCESS'
export const BUY_LOTTERY_NCC_FAILED = 'BUY_LOTTERY_NCC_FAILED'

export const DRAW_HISTORY = 'DRAW_HISTORY'
export const DRAW_HISTORY_SUCCESS = 'DRAW_HISTORY_SUCCESS'
export const DRAW_HISTORY_FAILED = 'DRAW_HISTORY_FAILED'

export const DRAW_HISTORY340 = 'DRAW_HISTORY340'
export const DRAW_HISTORY_SUCCESS340 = 'DRAW_HISTORY_SUCCESS340'
export const DRAW_HISTORY_FAILED340 = 'DRAW_HISTORY_FAILED340'

export const GET_PACKAGE_APA = 'GET_PACKAGE_APA'
export const GET_PACKAGE_APA_SUCCESS = 'GET_PACKAGE_APA_SUCCESS'
export const GET_PACKAGE_APA_FAILED = 'GET_PACKAGE_APA_FAILED'

// requestGetPackageOption

export const GET_PACKAGE_OPTION_APA = 'GET_PACKAGE_OPTION_APA'
export const GET_PACKAGE_OPTION_APA_SUCCESS = 'GET_PACKAGE_OPTION_APA_SUCCESS'
export const GET_PACKAGE_OPTION_APA_FAILED = 'GET_PACKAGE_OPTION_APA_FAILED'

export const PAY_MENT_INSURANCE = 'PAY_MENT_INSURANCE'
export const PAY_MENT_INSURANCE_SUCCESS = 'PAY_MENT_INSURANCE_SUCCESS'
export const PAY_MENT_INSURANCE_FAILED = 'PAY_MENT_INSURANCE_FAILED'

export const SET_LOGGED_IN_NOINTERNET = 'SET_LOGGED_IN_NOINTERNET'
export const LOGOUT_IN_NOINTERNET = 'LOGOUT_IN_NOINTERNET'

// worldBankList

export const WORK_BANK_OFFLINE_SERVICE = 'WORK_BANK_OFFLINE_SERVICE'
export const WORK_BANK_OFFLINE_SERVICE_SUCCESS = 'WORK_BANK_OFFLINE_SERVICE_SUCCESS'
export const WORK_BANK_OFFLINE_SERVICE_FAILED = 'WORK_BANK_OFFLINE_SERVICE_FAILED'


export const PAY_MENT_WATTER_NPP = 'PAY_MENT_WATTER_NPP'
export const PAY_MENT_WATTER_NPP_SUCCESS = 'PAY_MENT_WATTER_NPP_SUCCESS'
export const PAY_MENT_WATTER_NPP_FAILED = 'PAY_MENT_WATTER_NPP_FAILED'

export const CHECK_ACCUONT_WATTE = 'CHECK_ACCUONT_WATTE'
export const CHECK_ACCUONT_WATTE_SUCCESS = 'CHECK_ACCUONT_WATTE_SUCCESS'
export const CHECK_ACCUONT_WATTE_FALSE = 'CHECK_ACCUONT_WATTE_FALSE'


export const REQUES_HISTORY_TRANFER_NEW = 'REQUES_HISTORY_TRANFER_NEW'
export const REQUES_HISTORY_TRANFER_NEW_SUCCESS = 'REQUES_HISTORY_TRANFER_NEW_SUCCESS'
export const REQUES_HISTORY_TRANFER_NEW_FAILED = 'REQUES_HISTORY_TRANFER_NEW_FAILED'


export const GET_PROVINCE = 'GET_PROVINCE'
export const GET_PROVINCE_SUCCESS = 'GET_PROVINCE_SUCCESS'
export const GET_PROVINCE_FAILED = 'GET_PROVINCE_FAILED'


export const GET_DISTRICT = 'GET_DISTRICT'
export const GET_DISTRICT_SUCCESS = 'GET_DISTRICT_SUCCESS'
export const GET_DISTRICT_FAILED = 'GET_DISTRICT_FAILED'


export const GET_TOKEN_WORLD_BANK = 'GET_TOKEN_WORLD_BANK'
export const GET_TOKEN_WORLD_BANK_SUCCESS = 'GET_TOKEN_WORLD_BANK_SUCCESS'
export const GET_TOKEN_WORLD_BANK_FAILED = 'GET_TOKEN_WORLD_BANK_FAILED'



export const UPLOAD_TO_SERVER = 'UPLOAD_TO_SERVER'
export const UPLOAD_TO_SERVER_SUCCESS = 'UPLOAD_TO_SERVER_SUCCESS'
export const UPLOAD_TO_SERVER_FAILED = 'UPLOAD_TO_SERVER_FAILED'


export const CHECK_INFO_PAYMENT = 'CHECK_INFO_PAYMENT'
export const CHECK_INFO_PAYMENT_SUCCESS = 'CHECK_INFO_PAYMENT_SUCCESS'
export const CHECK_INFO_PAYMENT_FAILED = 'CHECK_INFO_PAYMENT_FAILED'

export const CHECK_INFO_DISCOUNT = 'CHECK_INFO_DISCOUNT'
export const CHECK_INFO_DISCOUNT_SUCCESS = 'CHECK_INFO_DISCOUNT_SUCCESS'
export const CHECK_INFO_DISCOUNT_FAILED = 'CHECK_INFO_DISCOUNT_FAILED'

export const HIGH_SECURITY_OTP = 'HIGH_SECURITY_OTP'
export const HIGH_SECURITY_OTP_SUCCESS = 'HIGH_SECURITY_OTP_SUCCESS'
export const HIGH_SECURITY_OTP_FAILED = 'HIGH_SECURITY_OTP_FAILED'

export const CALL_CHECK_SWICH = 'CALL_CHECK_SWICH'
export const CALL_CHECK_SWICH_SUCCESS = 'CALL_CHECK_SWICH_SUCCESS'
export const CALL_CHECK_SWICH_FAILED = 'CALL_CHECK_SWICH_FAILED'

export const CALL_CHECK_AMOUNT = 'CALL_CHECK_AMOUNT'
export const CALL_CHECK_AMOUNT_SUCCESS = 'CALL_CHECK_AMOUNT_SUCCESS'
export const CALL_CHECK_AMOUNT_FAILED = 'CALL_CHECK_AMOUNT_FAILED'

export const GET_ALL_CONFIG_AMOUNT = 'GET_ALL_CONFIG_AMOUNT'
export const GET_ALL_CONFIG_AMOUNT_SUCCESS = 'GET_ALL_CONFIG_AMOUNT_SUCCESS'
export const GET_ALL_CONFIG_AMOUNT_FAILED = 'GET_ALL_CONFIG_AMOUNT_FAILED'



export const GET_MEDIA_POPUP_HOME = 'GET_MEDIA_POPUP_HOME'
export const GET_MEDIA_POPUP_HOME_SUCCESS = 'GET_MEDIA_POPUP_HOME_SUCCESS'
export const GET_MEDIA_POPUP_HOME_FAILED = 'GET_MEDIA_POPUP_HOME_FAILED'

export const CHECK_BLOCK_DEVICE = 'CHECK_BLOCK_DEVICE'
export const CHECK_BLOCK_DEVICE_SUCCESS = 'CHECK_BLOCK_DEVICE_SUCCESS'
export const CHECK_BLOCK_DEVICE_FAILED = 'CHECK_BLOCK_DEVICE_FAILED'


export const GET_MENU_HOME = 'GET_MENU_HOME'
export const GET_MENU_HOME_SUCCESS = 'GET_MENU_HOME_SUCCESS'
export const GET_MENU_HOME_FAILED = 'GET_MENU_HOME_FAILED'

export const CALL_WEBVIEW_BADU_TOKEN = 'CALL_WEBVIEW_BADU_TOKEN'
export const CALL_WEBVIEW_BADU_TOKEN_SUCCESS = 'CALL_WEBVIEW_BADU_TOKEN_SUCCESS'
export const CALL_WEBVIEW_BADU_TOKEN_FAILED = 'CALL_WEBVIEW_BADU_TOKEN_FAILED'

export const CALL_WEBVIEW_BADU = 'CALL_WEBVIEW_BADU'
export const CALL_WEBVIEW_BADU_SUCCESS = 'CALL_WEBVIEW_BADU_SUCCESS'
export const CALL_WEBVIEW_BADU_FAILED = 'CALL_WEBVIEW_BADU_FAILED'


export const CALL_WEBVIEW_MY_UNITEL = 'CALL_WEBVIEW_MY_UNITEL'
export const CALL_WEBVIEW_MY_UNITEL_SUCCESS = 'CALL_WEBVIEW_MY_UNITEL_SUCCESS'
export const CALL_WEBVIEW_MY_UNITEL_FAILED = 'CALL_WEBVIEW_MY_UNITEL_FAILED'

export const CALL_LINK_WEBVIEW = 'CALL_LINK_WEBVIEW'
export const CALL_LINK_WEBVIEW_SUCCESS = 'CALL_LINK_WEBVIEW_SUCCESS'
export const CALL_LINK_WEBVIEW_FAILED = 'CALL_LINK_WEBVIEW_FAILED'


export const CALL_GET_MENU_LEVEL_2 = 'CALL_GET_MENU_LEVEL_2'
export const CALL_GET_MENU_LEVEL_2_SUCCESS = 'CALL_GET_MENU_LEVEL_2_SUCCESS'
export const CALL_GET_MENU_LEVEL_2_FAILED = 'CALL_GET_MENU_LEVEL_2_FAILED'