const images = {
  icLoginAgent: require('../images/Icons/icLoginAgent.png'),
  bg_umoney: require('../images/Icons/bg_umoney.png'),
  bg_footerLogin: require('../images/Icons/bg_footerLogin.png'),
  icLaos: require('../images/Icons/ic_laosLang.png'),
  icEnglish: require('../images/Icons/ic_englishLang.png'),
  icVietnam: require('../images/Icons/ic_vietnamLang.png'),
  icChina: require('../images/Icons/ic_chineseLang.png'),


  ic_laosLang: require('../images/Icons/ic_laosLang.png'),
  ic_chineseLang: require('../images/Icons/ic_chineseLang.png'),
  ic_englishLang: require('../images/Icons/ic_englishLang.png'),
  ic_vietnamLang: require('../images/Icons/ic_vietnamLang.png'),


  tab_home: require('../images/ic_newSceen/tab_home.png'),
  tab_any: require('../images/ic_newSceen/tab_any.png'),
  tab_unit: require('../images/ic_newSceen/tab_unit.png'),
  tab_history: require('../images/ic_newSceen/tab_history.png'),
  tab_user: require('../images/ic_newSceen/tab_user.png'),

  bannerPopupHome: require('../images/ic_newSceen/bannerPopupHome.jpg'),
  bannerGame: require('../images/ic_newSceen/bannerGame.png'),
  btnPlay: require('../images/ic_newSceen/btnPlay.png'),
  btnClose: require('../images/ic_newSceen/btnClose.png'),
  icGame: require('../images/ic_newSceen/icGame.png'),
  icNCCLottery: require('../images/ic_newSceen/icNCCLottery.png'),
  icBuyLottery: require('../images/ic_newSceen/icBuyLottery.png'),
  icAbout: require('../images/ic_newSceen/icAbout.png'),
  ic_topup: require('../images/ic_newSceen/ic_topup.png'),
  ic_Register: require('../images/ic_newSceen/ic_Register.png'),
  ic_Requestumoney: require('../images/ic_newSceen/ic_Requestumoney.png'),
  ic_RequestCash: require('../images/ic_newSceen/ic_RequestCash.png'),
  ic_Deposit: require('../images/ic_newSceen/ic_Deposit.png'),
  ic_SokxayLottery: require('../images/ic_newSceen/ic_SokxayLottery.png'),
  ic_Transfer: require('../images/ic_newSceen/ic_Transfer.png'),
  ic_CashOutNew: require('../images/ic_newSceen/ic_CashOut.png'),
  bg_headerAccout: require('../images/ic_newSceen/bg_header.png'),
  bg_headerAccout1: require('../images/ic_newSceen/bg_header1.png'),
  ic_profile: require('../images/ic_newSceen/ic_profile.png'),
  ic_changePIN: require('../images/ic_newSceen/ic_tranfer.png'),
  ic_About: require('../images/ic_newSceen/ic_About.png'),
  ic_callSupport: require('../images/ic_newSceen/ic_callSupport.png'),
  ic_Language: require('../images/ic_newSceen/ic_Language.png'),
  ic_TermCondition: require('../images/ic_newSceen/ic_TermCondition.png'),
  ic_Logout: require('../images/ic_newSceen/ic_logoutNew.png'),
  ic_FingerPrint: require("../images/Icons/ic_fingerprint.jpg"),
  mdi_settings: require('../images/ic_newSceen/mdi_settings.png'),

  tab_home: require('../images/ic_newSceen/tab_home.png'),
  tab_any: require('../images/ic_newSceen/tab_any.png'),
  tab_unit: require('../images/ic_newSceen/tab_unit.png'),
  tab_history: require('../images/ic_newSceen/tab_history.png'),
  tab_user: require('../images/ic_newSceen/tab_user.png'),

  ic_QRScan: require('../images/ic_newSceen/ic_QRScan.png'),

  icSecondPromo: require('../images/ic_newSceen/second_promo.jpg'),
  ic_pomotion: require('../images/ic_newSceen/img_pomotion.png'),
  ic_promotion20: require('../images/ic_newSceen/baner_promotion20.png'),
  ic_promotion50: require('../images/ic_newSceen/banner_promotion50.png'),

  icRevert: require('../images/ic_newSceen/ic_ChangePIN_2.png'),
  icAlphabet: require('../images/ic_newSceen/ic_Language_2.png'),
  ic_Fingerprint: require('../images/ic_newSceen/ic_Fingerprint.png'),

  bg_Ellipse: require('../images/ic_newSceen/bg_Ellipse.png'),
  mdi_face: require('../images/ic_newSceen/mdi_face.png'),
  ic_FindNearbyPOS: require('../images/ic_newSceen/ic_FindNearbyPOS.png'),
  ic_historyTranfer: require('../images/ic_newSceen/ic_historyTranfer.png'),

  ic_successfully: require('../images/ic_newSceen/ic_successfully.png'),
  ic_internet_new: require('../images/ic_newSceen/ic_internet.png'),
  ic_Leasing: require('../images/ic_newSceen/ic_Leasing.png'),
  ic_buydata: require('../images/ic_newSceen/ic_buydata.png'),
  ic_logiSent: require('../images/ic_newSceen/ic_logiSent.png'),
  ic_tranferToBank: require('../images/ic_newSceen/ic_tranferToBank.png'),
  ic_LVIInsurance: require('../images/ic_newSceen/ic_LVIInsurance.png'),
  icWaterBill: require('../images/ic_newSceen/icWaterBill.png'),
  ic_ElectricityBill: require('../images/ic_newSceen/ic_ElectricityBill.png'),

  screenHome: require('../images/ic_newSceen/ScreenHome.png'),
  ScreenHome01: require('../images/ic_newSceen/ScreenHome01.png'),
  ScreenHome02: require('../images/ic_newSceen/ScreenHome02.png'),
  ic_scrach: require('../images/ic_newSceen/ic_scrach.png'),

  ic_umoneyConf: require('../images/ic_newSceen/ic_umoneyConf.png'),

  ic_promotion01: require('../images/ic_newSceen/promotion01.jpeg'),
  ic_promotion02: require('../images/ic_newSceen/promotion02.jpeg'),
  ic_promotion03: require('../images/ic_newSceen/promotion03.jpeg'),


  icLoanOnlinePay: require('../images/ic_newSceen/ic_aecon.png'),
  icTranfer: require('../images/Icons/icTranfer.png'),
  ic_welcome: require('../images/ic_newSceen/ic_welcome.png'),
  ic_aecon: require('../images/ic_newSceen/ic_aecon.png'),

  icUnitel: require('../images/Icons/unitel_logo.png'),
  icEtl: require('../images/Icons/etl_logo.png'),
  icLTC: require('../images/Icons/icLTC.png'),


  logo_bcel: require('../images/ic_bank/logo_bcel.png'),
  logo_jdbbank: require('../images/ic_bank/logo_jdbbank.png'),
  logo_laovietbank: require('../images/ic_bank/logo_laovietbank.png'),
  logo_ldbbank: require('../images/ic_bank/logo_ldbbank.png'),
  logo_maruhanbank: require('../images/ic_bank/logo_maruhanbank.png'),
  ic_mt: require('../images/ic_bank/ic_mt.png'),
  ic_bankS: require('../images/ic_bank/ic_bank.png'),
  ic_acleda: require('../images/ic_bank/ic_acleda.png'),
  ic_bic: require('../images/ic_bank/ic_bicBank.png'),
  ic_mayBank: require('../images/ic_bank/ic_mayBank.png'),
  ic_apb: require('../images/ic_bank/ic_apb.png'),

  iconTest: require('../images/ic_newSceen/iconTest.png'),

  ic_buyLottery: require('../images/Icons/ic_buyLottery.png'),
  ic_checkLottery: require('../images/Icons/ic_checkLottery.png'),
  ic_saleLottery: require('../images/Icons/ic_saleLottery.png'),
  ic_lettery: require('../images/ic_newSceen/ic_lettery.png'),
  ic_Animal: require('../images/Animal/ic_Animal.png'),
  ic_dislike: require('../images/ic_newSceen/ic_dislike.png'),

  icCheckedBox: require('../images/Icons/checked_box.png'),
  icUncheckedBox: require('../images/Icons/unchecked_box.png'),
  logoDetale: require('../images/Icons/logoDetale.png'),
  icPodium: require('../images/Icons/icPodium.png'),

  iconetl: require('../images/Icons/icon-etl.png'),
  iconltc: require('../images/Icons/icon-ltc.png'),
  iconunitel: require('../images/Icons/icon-unitel.png'),
  ic_worldBank: require('../images/Icons/ic_worldBank.png'),

  iconWinner: require('../images/ic_lottery/iconWinner.png'),

  iconDigits1D: require('../images/ic_lottery/icon_1D_Ball.png'),
  iconDigits2D: require('../images/ic_lottery/icon_2D_Ball.png'),
  iconDigits3D: require('../images/ic_lottery/icon_3D_Ball.png'),
  iconDigits4D: require('../images/ic_lottery/icon_4D_Ball.png'),
  iconDigits5D: require('../images/ic_lottery/icon_5D_Ball.png'),
  iconDigits6D: require('../images/ic_lottery/icon_6D_Ball.png'),
  iocnAnimalBall: require('../images/ic_lottery/iocnAnimalBall.png'),
  iocnDelete: require('../images/ic_lottery/iocnDelete.png'),
  iconShare: require('../images/ic_newSceen/iconShare.png'),
  iconSave: require('../images/ic_newSceen/iconSave.png'),
  logoInQR: require('../images/ic_newSceen/logoInQR.png'),
  icSaveHistory: require('../images/ic_newSceen/saving_history.png'),
  icon_call: require('../images/ic_newSceen/icon_call.png'),
  icon_Share: require('../images/ic_newSceen/icon_Share.png'),
  icon2share: require('../images/ic_newSceen/icon2share.png'),
  iconCopy: require('../images/ic_newSceen/iconCopy.png'),
  iconAPA: require('../images/ic_newSceen/iconAPA.png'),
  logoTplus: require('../images/ic_newSceen/logoTplus.jpg'),
  APAInsuranceBenefits: require('../images/ic_newSceen/APAInsuranceBenefits.png'),
  ic_ADSL: require('../images/Icons/ic_ADSL.png'),
  ic_FTTH: require('../images/Icons/ic_FTTH.png'),
  ic_LeasedLine: require('../images/Icons/ic_LeasedLine.png'),
  ic_HighSecurity: require('../images/Icons/Vector.png'),
  ic_Vector: require('../images/Icons/ic_Vector.png'),
  iconStem: require('../images/Icons/iconStem.png'),

  ic_UnitelSaler:require('../images/Icons/ic_UnitelSaler.png'),
  ic_UnitelServices:require('../images/Icons/ic_UnitelServices.png'),
  ic_UnitelShop:require('../images/Icons/ic_UnitelShop.png'),

  icStamp_cn: require('../images/Icons/icStamp_cn.png'),
  icStamp_la: require('../images/Icons/icStamp_la.png'),
  icStamp_vi: require('../images/Icons/icStamp_vi.png'),
  iconDefault: require('../images/Icons/iconDefault.png'),




}
export default images
